### ISSUE TITLE
MCP server launch intermittently fails with 'Cannot find module ajv' from a partially-populated npx cache

### ISSUE THREAD

**Issue by tadasant** [tadasant/zimmer#435]
🚦 ## What I observed

Two consecutive agent sessions on 2026-08-14 had an MCP server fail its **first** connection attempt with a `MODULE_NOT_FOUND` for `ajv`, thrown from inside the per-session npx cache:

```
Error: Cannot find module 'ajv'
Require stack:
- <clone>/.npm-cache/_npx/<hash>/node_modules/ajv-formats/dist/limit.js
- <clone>/.npm-cache/_npx/<hash>/node_modules/ajv-formats/dist/index.js
    at Function._resolveFilename (node:internal/modules/cjs/loader:1430:15)
    ...
Node.js v22.23.2
 | Connection failed after ~8s (CONNECTION_CLOSED): Connection closed
```

- **Session 4317**, 07:32 UTC — an SSH-backed server failed this way, then connected at 07:32:38 after the retry.
- **Session 4325**, 08:03 UTC — a *different* server (Slack) failed identically, with a different `_npx/<hash>` directory, then connected at 08:04:21 after the retry.

Both sessions recorded `mcp_retry_count: 1` and both listed the server under `mcp_failed_servers` with `status: "failed"` even after the retry had succeeded. In session 4325 the agent job itself was replaced (the initial job ID differs from the running job ID), so this was not a silent in-process reconnect.

`ajv-formats` declares `ajv` as a peer dependency. A partially-populated or concurrently-written `_npx/<hash>` tree therefore resolves `ajv-formats` while `ajv` itself is still absent, and the server process exits before it can speak MCP.

## Why it's wrong

The failure is in cache *provisioning*, not in the server, so it hits servers that are otherwise fine and it hits them nondeterministically — two different servers on two different sessions within 30 minutes. Concretely it costs:

1. **~8 seconds per failed attempt plus a full job restart** on every occurrence.
2. **A real risk of a session running without a tool it needs.** The retry is what saved both of these. Session 4325's entire deliverable was a Slack reply, and Slack was the server that failed — had the retry not succeeded, the session would have run to completion with no way to report, and nothing in the flow would have caught it.
3. **A misleading `mcp_failed_servers` entry that is never cleared on success**, so post-hoc inspection of a healthy session shows a server marked `failed`. Anything reasoning about session health from that field will read it wrong.

## Workaround / impact

None was needed — the built-in retry recovered both times. But the recovery is luck rather than design: the observed sequence is "fail, restart the job, succeed", and there is no guard that the second attempt lands. Two candidate fixes, in increasing order of thoroughness:

- Make the npx cache population atomic (populate a temp dir, then rename), so a partially-written tree is never resolvable.
- Verify a freshly-provisioned server's dependency tree before launching it, or pre-install rather than relying on `npx` to populate per-clone.

Separately and more cheaply: clear a server's `mcp_failed_servers` entry once a later attempt connects, so the field reflects final state.

---
*Filed by an agent that observed this while triaging an unrelated production alert. Not a human-reported defect; see the `agent-filed` label.*

**Comment by tadasant** [comment]
Third occurrence, and the **first one that did not recover** — it terminally orphaned a production session. This also supplies the causal mechanism the earlier comments were circling, and it bears directly on the gate's **A5 ("possibly already addressed by `NpxCacheHealService`")** hold reason.

## What happened (2026-08-15)

| Time (UTC) | Event |
|---|---|
| 09:24:29 | `npx` install fails: `ENOTEMPTY` renaming `_npx/<hash>/node_modules/cross-spawn` |
| 09:25:11 | Retry fails: `ENOTEMPTY` on `_npx/<hash>/node_modules/onepassword-mcp-server` |
| 09:28:34 | Retry fails: `ENOTEMPTY` on `_npx/<hash>/node_modules/zod` |
| 09:28:37 | `MCP server(s) failed to connect: 1password-pulsemcp-rw` |
| 09:28:38 | **`MCP servers failed to connect — session orphaned after 3 retries`** — production session terminally orphaned |
| 09:33:51 | A human manually removes the server from the session |
| 09:34:06 | Session restarted by hand; it then runs fine |

This paged `#alerts` via the `Zimmer backend logging errors (excludes staging)` Grafana rule — the single ERROR record in that 5m window.

## The mechanism: two servers, one `_npx/<hash>`, one clone

The session had **both `1password-tadas-rw` and `1password-pulsemcp-rw`** attached. Both are `npx onepassword-mcp-server` wrappers over different vaults, so **both resolve to the same npx hash directory** — `_npx/04f14e66d79e7af4` — and both install into it *simultaneously, inside a single clone*.

That is visible directly in the logs: failures under that **same** hash are attributed to **both** servers (`1password-tadas-rw` on `cross-spawn`, `1password-pulsemcp-rw` on `onepassword-mcp-server` and `zod`).

The prior comments observed concurrency across *different clones*. This is concurrency **inside one clone's cache** — precisely the case the per-clone `NPM_CONFIG_CACHE=<clone>/.npm-cache` isolation was designed to rule out. Per-clone isolation is not fine-grained enough: it partitions by clone, but the race is between two servers *sharing a package spec* within a clone.

## Why this rebuts A5

`NpxCacheHealService`'s strategy is "delete the poisoned `_npx/<hash>` tree so the next retry re-installs cleanly." That is correct for a **static** corrupt tree that otherwise sticks. It cannot win here, for two reasons:

1. **The race is live, not static.** Each of the three retries failed on a *different* package (`cross-spawn` → `onepassword-mcp-server` → `zod`). A poisoned-and-stuck tree fails the same way every time; a moving failure point is the signature of a concurrent writer still active.
2. **Heal-by-delete re-arms the race.** Deleting the shared tree while a sibling server is mid-install destroys that sibling's in-flight extraction, which is itself a fresh `ENOTEMPTY`/`TAR_ENTRY_ERROR` source. With two servers both retrying into one directory, healing feeds the loop rather than ending it.

So the heal service is not a mitigation for this variant — it is arguably a contributor. All three retries were burned and the session was orphaned.

## Standing exposure

This is not a one-off pairing. At the time of triage, multiple live sessions had **both** 1Password servers attached simultaneously (sessions 4658, 4666, 4672), so any session configured with two servers sharing an npx package spec is exposed on every boot.

## Bearing on the fix

Both fixes already proposed in the issue body still apply, and this occurrence argues for the stronger one:

- **Atomic cache population** (populate a temp dir, then rename) fixes the partial-tree read but not two writers contending for one destination.
- **Pre-install rather than relying on `npx` to populate per-clone** — or **serialize/lock `_npx/<hash>` population per hash**, or key the cache per *server* rather than per *clone* — addresses the contention itself.

A per-hash install lock is the smallest change that makes the two-servers-one-package case correct.

---
*Added by an agent triaging the `Zimmer backend logging errors (excludes staging)` alert that this orphaning fired. Evidence only — I did not spawn work against this issue, since it is under an explicit gate HOLD.*

**Comment by tadasant** [comment]
**Recurrence calibration, and a variant that this issue's proposed fixes would not catch.**

The orphaning reported in the comment above (09:28:38Z) **recurred twice more within 31 minutes**, on the same session (4388), each time paging `#alerts`:

| Time (UTC) | Failing servers | Stderr | Outcome |
|---|---|---|---|
| 09:28:38 | `1password-pulsemcp-rw` | `ENOTEMPTY` — a **different package each retry** (`cross-spawn` → `onepassword-mcp-server` → `zod`) | orphaned |
| 09:56:30 | `1password-tadas-rw` | `sh: 1: onepassword-mcp-server: Permission denied` | orphaned |
| 09:59:17 | `1password-tadas-rw` (+ `1password-pulsemcp-rw`) | same, **identical on all 3 retries** | orphaned |

So: **three terminal orphanings of one production session inside 31 minutes**, two Grafana pages (09:34:28Z and 09:59:28Z), and a human had to remove the server by hand at 10:07:40Z to unblock it. That is the recurrence rate this issue did not previously have.

**But the second and third are a different failure mode, and I filed them separately as #467.** The 09:28 occurrence is this issue: a live write-write race, moving failure point. The 09:56/09:59 occurrences are a *stably wrong* tree — the `.bin` symlink was created but its target `build/index.js` was left `-rw-r--r--`, so exec returns `EACCES` identically on every retry. I confirmed on disk that the tarball for `onepassword-mcp-server@0.5.4` ships that file without the exec bit, and that Zimmer renders every npx MCP command with an injected `--prefix /tmp` (absent from all 72 catalog entries) that aims npm's bin-linking at a `/tmp/node_modules/.bin` which does not exist on the host.

Two things follow that bear on this issue:

1. **The fixes proposed here would not have prevented the 09:56/09:59 orphanings.** Atomic cache population and a per-hash install lock both address contention; neither sets a missing mode bit. Worth scoping #467 alongside this rather than assuming one fix covers both.
2. **`--prefix /tmp` is plausibly a contributor to *this* issue too.** It points npm at a host-shared directory, so the per-clone `NPM_CONFIG_CACHE` isolation this issue's earlier comments rely on is not as isolating as it looks — concurrency across clones is back on the table, not just within one.

---
*Added by an agent triaging the 09:59:28Z firing of the `Zimmer backend logging errors (excludes staging)` alert. Evidence only — no work spawned against this issue, which remains under its gate HOLD. Context: https://zimmer.tadasant.com/sessions/4717*

**Comment by tadasant** [comment]
## Backlog groom — sibling pointer

Grouped with [#498](https://github.com/tadasant/zimmer/issues/498) as one convergent cluster about npx cache ownership; the anchor comment with the reasoning is [there](https://github.com/tadasant/zimmer/issues/498#issuecomment-5306300682).

Filed by the nightly backlog groomer (fleet-maintenance root), 2026-08-16.

**Comment by tadasant** [comment]
Re-verified on `main` (`a6c1251`). **Substantial remediation landed, but not the fixes this issue asked for. Partial — leaving open.**

**Fixed, by merged PRs.** The reproducible cause the 2026-08-15 comment identified — two servers sharing one npx package spec inside one clone — is now *prevented* rather than repaired:

- `app/services/npx_cache_isolator.rb` (**PR #475**, `c5bc8001`, merged 2026-08-16) gives each colliding stdio entry its own `NPM_CONFIG_CACHE` under `.npm-cache/isolated/<server>/`, and writes the cache location into every npx entry's own `env` rather than relying on process inheritance. Its header at `:35-44` names the `1password-tadas-rw` / `1password-pulsemcp-rw` pair and production session 4668 from that comment.
- `--prefix /tmp`, flagged in the 10:19 comment as a contributor, is gone — `app/services/npx_bin_executable_guard.rb:21` records it and `runtime_config_post_processor.rb:26` enforces it (**PR #471**).
- `app/services/npx_cache_layout.rb` (**PR #797**) gives the path shape one owner, so the heal service, the bin guard and `CacheClearService` all reach isolated roots.
- The cheap third ask is done: `mcp_failed_servers` is in `STALE_MCP_FAILURE_KEYS` (`session_state_machine.rb:1788-1793`) and dropped on resume (`:1840`, `:1855-1857`); `mcp_status_persisting.rb:113-115` retires a write-off when a degraded server reconnects.
- All three siblings — **#467, #498, #595** — are closed.

**Not fixed: both remedies this body proposed.** There is no atomic cache population (populate a temp dir, then rename) and no pre-install / dependency-tree verification before launch. I grepped for any install lock — `flock|File::LOCK` across `app/services/npx_*.rb` returns nothing; the `File.rename` mention at `npx_cache_heal_service.rb:92` is prose about npm's own rename. `npx_cache_isolator.rb:52-54` draws the boundary itself:

> *"Only *colliding* servers get a root of their own… `NpxCacheHealService` still cleans up after a corruption that happens anyway; this stops the one cause Zimmer can see coming."*

So the general partially-populated-tree case — a killed install, a full disk — is still handled by detect-and-delete after the fact, which is what this issue argued against. This issue's `ajv` trace is still quoted verbatim as a *current* signature at `npx_cache_heal_service.rb:29-32`. None of the PRs above carries a closing keyword for #435 and no commit message references it.

**⚠️ Flagging, not folding:** `tadasant/tadasant-internal#1738` (*"playwright-custom fails to launch: 'Cannot find module ajv' from a corrupted npx cache"*, OPEN) looks like the **same root cause**, differing only in which cache. That is a cross-repo pair and a human's call; I have commented there too.

**The A5 hold reason is void**; reported back for a fresh rating. No labels changed.

Checked by the fleet-maintenance root's A5 staleness sweep, 2026-09-06.

**Comment by tadasant** [comment]
## 🚦 Issue gate

**Kind:** `bug` (⚪ normal) · **Scope:** convergent · **Facets:** none

**Verdict: HELD — A5.** This is a **re-rate** under the posture that took effect on 2026-09-06, and the previous hold's grounds are gone. Held on the staleness finding recorded at the previous rating: the `Cannot find module 'ajv'` symptom traced to a partially-populated npx cache, and `fix(mcp): pin every npx MCP server's npm cache inside the clone` (#595) and `fix(mcp): give the npx cache layout one owner, so the bin guard reaches isolated roots` (#498) have both merged since the issue was filed. Re-checked against the merged-PR corpus today; nothing contradicts it.

**Live pages:** none — Grafana's provisioning and rule-state endpoints report **no rule in `firing` or `pending` state anywhere** (`GET /api/prometheus/grafana/api/v1/rules`, non-inactive rules: `[]`), and this issue is not an ask about a specific rule's firing behaviour in any case. Normal dispatch — nothing spawned.

<details>
<summary>Why this was re-rated, and what changed</summary>

On **2026-09-06** Tadas retired five of the issue gate's eight hold tests: **A1** (self-escalation), **A2** (never-auto kinds and every per-surface permanent-exclusion list), **A3** (it expands product scope), **A6** (you cannot say what "done" looks like) and **A8** (triviality). All five numbers are burned rather than reused. In his words, generalising from self-modification: *"it IS a valid reason to not merge it automatically, but that's a merge gate problem, not an issue gate problem."*

**The issue gate now asks exactly two questions — is this input safe to act on, and can an agent actually finish it — plus A7 as a carve-out for work that happens before any PR exists.** Every other risk judgment now sits with the `pr-merge-gate`, on the real diff.

**This issue is still held**, but on a test that survived that retirement: **A5**. That is a different ground from the one the earlier verdict on this issue named, and it is stated above rather than inherited.

</details>

<details>
<summary>Rating detail</summary>

The five axes are recorded for the ledger and **did not decide this**; under `ISSUE_WORK_GATE_POSTURE.md` a `large` rating holds nothing.

| Axis | Rating | Why |
|---|---|---|
| Requirement complexity | small | carried forward from the prior rating on this issue; re-checked, not re-derived. |
| Requirement impact | large | carried forward from the prior rating on this issue; re-checked, not re-derived. |
| Solution complexity | medium *(est.)* | carried forward from the prior rating on this issue; re-checked, not re-derived. |
| Implementation risk | large *(est.)* | carried forward from the prior rating on this issue; re-checked, not re-derived. |
| Estimated cost | medium *(est.)* | carried forward from the prior rating on this issue; re-checked, not re-derived. |

**Note:** the three solution-side axes are **estimates** — there is no diff yet.

**Staleness check (5c):** **possibly stale.** Two merged PRs rework exactly the npx cache layout this intermittent failure was traced to. I could not confirm the symptom no longer reproduces — an intermittent failure is not disprovable from a checkout — only that the named cause has been reworked twice.

</details>

Re-entry: if the `Cannot find module` failure is observed again after #595 and #498, that observation makes this live and it will clear.

<sub>Re-rated by the 2026-09-06 posture sweep of the `hold issue work gate` pile on `tadasant/zimmer` (86 issues). [Session 15652](https://zimmer.tadasant.com/sessions/15652).</sub>

**Comment by tadasant** [comment]
Checked as a staleness candidate tonight and **left open** — the evidence retires most of this issue, not all of it.

**What has landed.** The cache-provisioning half is addressed: `fix(mcp): pin every npx MCP server's npm cache inside the clone` (#701, merged 2026-08-29, closing #595) and `fix(mcp): give the npx cache layout one owner, so the bin guard reaches isolated roots` (#797, merged 2026-09-02, closing #498) both sit on the path that produced the partially-populated `_npx/<hash>` tree described above.

**What is left.** The third item under *Why it's wrong*, restated in *Workaround / impact* as the cheap separable fix: **a `mcp_failed_servers` entry is never cleared once a later attempt connects**, so a healthy session still reads as having a failed server. I could not find a merged change on that, and nothing in the two PRs above touches it. Neither of the two candidate fixes named for the provisioning race (atomic populate-then-rename, or verify/pre-install before launch) was taken literally either — the pinning and ownership changes attack the same race from a different angle, which may well be enough, but that is a judgement for whoever picks this up rather than a fact I can point at.

So the close is not due: half an issue being dead is not a staleness close, and the remainder has no other issue carrying it. No labels were touched.

Reviewed by the nightly backlog groomer (fleet-maintenance root), 2026-09-12.
